version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: ["poetry", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/library_service"
      POSTGREST_HOST: "db"
      POSTGREST_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  grpc_server:
    build: .
    command: ["poetry", "run", "python", "app/grpc_server.py"]
    environment:
      PYTHONPATH: /app
      DATABASE_URL: "postgres://postgres:postgres@db/library_service"
    ports:
      - "50051:50051"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
