# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"l\n\rMemberRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\"-\n\x0eMemberResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x0b\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\"+\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\rBorrowRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x05\"-\n\x0e\x42orrowResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\rReturnRequest\x12\x11\n\tborrow_id\x18\x01 \x01(\x05\"!\n\x0eReturnResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x13ListBorrowedRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x05\"S\n\x0c\x42orrowedBook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0b\x62orrow_date\x18\x04 \x01(\t\"<\n\x14ListBorrowedResponse\x12$\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x15.library.BorrowedBook2\xdc\x02\n\x0eLibraryService\x12?\n\x0c\x43reateMember\x12\x16.library.MemberRequest\x1a\x17.library.MemberResponse\x12\x39\n\nCreateBook\x12\x14.library.BookRequest\x1a\x15.library.BookResponse\x12=\n\nBorrowBook\x12\x16.library.BorrowRequest\x1a\x17.library.BorrowResponse\x12=\n\nReturnBook\x12\x16.library.ReturnRequest\x1a\x17.library.ReturnResponse\x12P\n\x11ListBorrowedBooks\x12\x1c.library.ListBorrowedRequest\x1a\x1d.library.ListBorrowedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERREQUEST']._serialized_start=26
  _globals['_MEMBERREQUEST']._serialized_end=134
  _globals['_MEMBERRESPONSE']._serialized_start=136
  _globals['_MEMBERRESPONSE']._serialized_end=181
  _globals['_BOOKREQUEST']._serialized_start=183
  _globals['_BOOKREQUEST']._serialized_end=241
  _globals['_BOOKRESPONSE']._serialized_start=243
  _globals['_BOOKRESPONSE']._serialized_end=286
  _globals['_BORROWREQUEST']._serialized_start=288
  _globals['_BORROWREQUEST']._serialized_end=339
  _globals['_BORROWRESPONSE']._serialized_start=341
  _globals['_BORROWRESPONSE']._serialized_end=386
  _globals['_RETURNREQUEST']._serialized_start=388
  _globals['_RETURNREQUEST']._serialized_end=422
  _globals['_RETURNRESPONSE']._serialized_start=424
  _globals['_RETURNRESPONSE']._serialized_end=457
  _globals['_LISTBORROWEDREQUEST']._serialized_start=459
  _globals['_LISTBORROWEDREQUEST']._serialized_end=499
  _globals['_BORROWEDBOOK']._serialized_start=501
  _globals['_BORROWEDBOOK']._serialized_end=584
  _globals['_LISTBORROWEDRESPONSE']._serialized_start=586
  _globals['_LISTBORROWEDRESPONSE']._serialized_end=646
  _globals['_LIBRARYSERVICE']._serialized_start=649
  _globals['_LIBRARYSERVICE']._serialized_end=997
# @@protoc_insertion_point(module_scope)
